; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env_common]
platform = espressif8266
board = esp12e
framework = arduino
monitor_speed = 115200
;board_build.flash_mode = dio
;board_build.ldscript = eagle.flash.4m1m.ld
build_flags =
    -DENABLE_SERIAL_LOG=0
    -DFW_VERSION=\"0.1.4-passionate_gimp\"
    -DTELEMETRY_INTERVAL_MS_CFG=300000UL
extra_scripts = post:post_build_ota.py
lib_deps =
    jchristensen/JC_Button@^2.1.6
    knolleary/PubSubClient@^2.8
    bblanchon/ArduinoJson@^7.4.2

[env:vacubear]
extends = env_common
build_flags =
    ${env_common.build_flags}
    -DOTA_MANIFEST_URL=\"http://ota.kingbear.de/vacubear/manifest.json\"
    -DLED_COUNT=4
    -Ivariants/vacubear

[env:ableger]
extends = env_common
build_flags =
    ${env_common.build_flags}
    -DOTA_MANIFEST_URL=\"http://ota.kingbear.de/ableger/manifest.json\"
    -DLED_COUNT=0
    -Ivariants/ableger

[env:esp12f]
extends = env:vacubear
